source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "jekyll-paginate-v2", "~> 2.0"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-gist", "~> 1.5"
gem "jekyll-feed", "~> 0.15.0"
gem "jekyll-data", "~> 1.1"
gem "jemoji", "~> 0.12"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.7"
